# Generated by Django 3.1.1 on 2020-09-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200913_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('price', models.FloatField()),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='LatestProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('price', models.FloatField()),
                ('url', models.URLField()),
            ],
        ),
    ]
