# Generated by Django 3.1.1 on 2020-09-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_featureproducts_latestproducts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featureproducts',
            name='url',
        ),
        migrations.RemoveField(
            model_name='latestproducts',
            name='url',
        ),
        migrations.AddField(
            model_name='featureproducts',
            name='dir_url',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='latestproducts',
            name='dir_url',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
